"""
RUN EVERYTHING - Complete Automation Script
One command to run: scraper, ETL, data warehouse, ML models, outputs, dashboard

How to run: python run_everything.py
"""

import subprocess
import sys
import time
import threading
from pathlib import Path
from datetime import datetime

print('='*140)
print("COMPLETE DATA PLATFORM - RUNNING EVERYTHING")
print(f"Start time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print('='*140)


def run_command(command, description):
    """
    Run a command and print result.
    """
    print(f"\n>>> {description}")
    print('-'*70)
    
    result = subprocess.run(command, shell=True, capture_output=True, text=True)
    
    if result.returncode == 0:
        print(f"SUCCESS: {description} completed")
    else:
        print(f"ERROR: {description} failed")
        print(f"Error: {result.stderr[:500]}")
        return False
    
    return True


def start_streamlit_dashboard():
    """
    Start Streamlit dashboard in a separate thread.
    """
    project_root = Path(__file__).parent
    dashboard_path = project_root / "05_analytics_dashboard" / "dashboard.py"
    
    print("\n>>> STARTING STREAMLIT DASHBOARD")
    print('-'*70)
    print(f"Dashboard will open at: http://localhost:8501")
    print("Close the terminal to stop the dashboard")
    print('-'*70)
    
    # Run streamlit in a separate process (not blocking)
    subprocess.Popen(
        f"streamlit run {dashboard_path}",
        shell=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )
    
    time.sleep(3)  # Wait for dashboard to start
    print("Streamlit dashboard started successfully")


def main():
    """
    Run all components in order.
    """
    
    project_root = Path(__file__).parent
    
    # Step 1: Run scraper
    print("\n" + "="*140)
    print("STEP 1: WEB SCRAPER")
    print("="*140)
    scraper_path = project_root / "01_data_collection" / "run_scraper.py"
    if not run_command(f"python {scraper_path} --auto", "Web Scraper"):
        print("Pipeline stopped: Scraper failed")
        return False
    
    # Step 2: Run ETL (includes loading to MySQL)
    print("\n" + "="*140)
    print("STEP 2: ETL PIPELINE")
    print("="*140)
    etl_path = project_root / "02_data_engineering" / "run_etl.py"
    # Auto-answer ETL prompts
    responses = "1\n1\n1\nyes\n"
    result = subprocess.run(
        f"echo {responses} | python {etl_path}",
        shell=True,
        capture_output=True,
        text=True
    )
    if result.returncode == 0:
        print("SUCCESS: ETL Pipeline completed")
    else:
        print(f"ERROR: ETL Pipeline failed: {result.stderr[:500]}")
        return False
    
    # Step 3: Populate data warehouse
    print("\n" + "="*140)
    print("STEP 3: DATA WAREHOUSE (Star Schema)")
    print("="*140)
    warehouse_path = project_root / "03_data_warehouse" / "populate_data_warehouse.py"
    run_command(f"python {warehouse_path}", "Data Warehouse Population")
    
    # Step 4: Train Linear Models
    print("\n" + "="*140)
    print("STEP 4: MACHINE LEARNING - LINEAR MODELS")
    print("="*140)
    linear_path = project_root / "04_data_science" / "01_train_linear_models.py"
    run_command(f"python {linear_path}", "Linear Models Training")
    
    # Step 5: Train Decision Tree
    print("\n" + "="*140)
    print("STEP 5: MACHINE LEARNING - DECISION TREE")
    print("="*140)
    tree_path = project_root / "04_data_science" / "02_train_decision_tree.py"
    run_command(f"python {tree_path}", "Decision Tree Training")
    
    # Step 6: Train Random Forest
    print("\n" + "="*140)
    print("STEP 6: MACHINE LEARNING - RANDOM FOREST")
    print("="*140)
    forest_path = project_root / "04_data_science" / "03_train_random_forest.py"
    run_command(f"python {forest_path}", "Random Forest Training")
    
    # Step 7: Train Gradient Boosting
    print("\n" + "="*140)
    print("STEP 7: MACHINE LEARNING - GRADIENT BOOSTING")
    print("="*140)
    gb_path = project_root / "04_data_science" / "04_train_gradient_boosting.py"
    run_command(f"python {gb_path}", "Gradient Boosting Training")
    
    # Step 8: Compare all models
    print("\n" + "="*140)
    print("STEP 8: MACHINE LEARNING - COMPARE MODELS")
    print("="*140)
    compare_path = project_root / "04_data_science" / "05_compare_all_models.py"
    run_command(f"python {compare_path}", "Model Comparison")
    
    # Step 9: Output files already generated by ETL
    print("\n" + "="*140)
    print("STEP 9: OUTPUT FILES")
    print("="*140)
    print("Output files are in:")
    print("  - output/exports/ (CSV files)")
    print("  - output/reports/ (Text reports)")
    print("  - output/dashboards/ (HTML dashboard)")
    
    # Step 10: Open static HTML dashboard
    print("\n" + "="*140)
    print("STEP 10: OPENING STATIC HTML DASHBOARD")
    print("="*140)
    dashboard_html = project_root / "output" / "dashboards" / "dashboard_latest.html"
    if dashboard_html.exists():
        subprocess.run(f"start {dashboard_html}", shell=True)
        print(f"HTML Dashboard opened: {dashboard_html}")
    else:
        print("Dashboard file not found. Run ETL first.")
    
    # Step 11: Start Streamlit live dashboard
    print("\n" + "="*140)
    print("STEP 11: STARTING STREAMLIT LIVE DASHBOARD")
    print("="*140)
    start_streamlit_dashboard()
    
    # Final summary
    print("\n" + "="*140)
    print("COMPLETE DATA PLATFORM - ALL TASKS COMPLETED")
    print(f"End time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*140)
    print("\nSUMMARY OF WHAT WAS RUN:")
    print("  1. Web Scraper - Collected new books")
    print("  2. ETL Pipeline - Cleaned and loaded to MySQL")
    print("  3. Data Warehouse - Populated star schema")
    print("  4. Machine Learning - Trained 4 models (Linear, Tree, Forest, Boosting)")
    print("  5. Model Comparison - Selected best model")
    print("  6. Output Files - Generated CSV, report, HTML dashboard")
    print("  7. HTML Dashboard - Opened in browser")
    print("  8. Streamlit Dashboard - Started at http://localhost:8501")
    print("\n" + "="*140)
    print("TO VIEW STREAMLIT DASHBOARD:")
    print("  Open your browser to: http://localhost:8501")
    print("="*140)
    
    return True


if __name__ == "__main__":
    try:
        success = main()
        if not success:
            print("\nPipeline had errors. Check logs above.")
            sys.exit(1)
    except KeyboardInterrupt:
        print("\n\nPipeline interrupted by user")
        sys.exit(1)
    except Exception as error:
        print(f"\nUnexpected error: {error}")
        sys.exit(1)